### ISSUE TITLE
ActionController issues with an 'undefined method `helper_method`'

### ISSUE THREAD

**Issue by BrennickL** [matiasgagliano/action_access#16]
Users/biosci/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.5/lib/action_controller/api.rb:110: warning: already initialized constant ActionController::API::MODULES
/Users/biosci/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.5/lib/action_controller/api.rb:110: warning: previous definition of MODULES was here

ActionController::RoutingError (undefined method `helper_method' for ActionController::API:Class):

app/controllers/application_controller.rb:1:in `<top (required)>'
app/controllers/api/postings_tables_controller.rb:1:in `<top (required)>'
/Users/biosci/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.5/lib/action_controller/api.rb:110: warning: already initialized constant ActionController::API::MODULES
/Users/biosci/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.5/lib/action_controller/api.rb:110: warning: previous definition of MODULES was here

**Comment by espen** [comment]
Duplicate of https://github.com/matiasgagliano/action_access/issues/12
